### ISSUE TITLE
"list index out of range" during reflection

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/reflector-cluster#19]
I see this in my logs when reflector does its hourly check. It may be some old downloads/bad blob data - thoughts? We should probably find a way to catch it properly. 

Not sure exactly which claim is happening on, so I'm attaching a couple samples. 

```
2017-10-14 07:54:13,528 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (ea60d6af75107702)
2017-10-14 07:54:13,582 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (05e5315bec119349)
2017-10-14 07:54:13,608 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://juliamichaels (6a54c4d93403400e)
2017-10-14 07:54:13,614 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://alexnmike (2b0967cd04686812)
2017-10-14 07:54:13,619 WARNING  lbrynet.reflector.client.client:39: An error occurred immediately: Traceback (most recent call last):
  File "site-packages\twisted\internet\base.py", line 1208, in mainLoop
    
  File "site-packages\twisted\internet\base.py", line 801, in runUntilCurrent
    
  File "site-packages\twisted\internet\defer.py", line 457, in callback
    
  File "site-packages\twisted\internet\defer.py", line 565, in _startRunCallbacks
    
--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    
  File "site-packages\lbrynet\reflector\client\client.py", line 161, in <lambda>
    
exceptions.IndexError: list index out of range

2017-10-14 07:54:13,665 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (a21e55fd35cff660)
2017-10-14 07:54:13,665 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (8244cc5172e04f63)
2017-10-14 07:54:13,742 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (31f8411cb068a78a)
2017-10-14 07:54:13,752 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://yearone-fullalbum (71707eab062ead18)
2017-10-14 07:54:13,815 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://culture-ep4 (74e44f53185fb651)
2017-10-14 07:54:13,819 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://themechanicalmonster (875b8322fd4d8af4)
2017-10-14 07:54:13,924 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (e2d5740a5c019678)
2017-10-14 07:54:13,946 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (92ad36e6d0d5331b)
2017-10-14 07:54:13,959 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (46c8249df0a21860) 
```

```
2017-10-14 08:54:12,484 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (05e5315bec119349)
2017-10-14 08:54:12,506 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://alexnmike (2b0967cd04686812)
2017-10-14 08:54:12,519 WARNING  lbrynet.reflector.client.client:39: An error occurred immediately: Traceback (most recent call last):
  File "site-packages\twisted\internet\base.py", line 1208, in mainLoop
    
  File "site-packages\twisted\internet\base.py", line 801, in runUntilCurrent
    
  File "site-packages\twisted\internet\defer.py", line 457, in callback
    
  File "site-packages\twisted\internet\defer.py", line 565, in _startRunCallbacks
    
--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    
  File "site-packages\lbrynet\reflector\client\client.py", line 161, in <lambda>
    
exceptions.IndexError: list index out of range

2017-10-14 08:54:12,576 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (8244cc5172e04f63)
2017-10-14 08:54:12,585 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (a21e55fd35cff660)
2017-10-14 08:54:12,618 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (31f8411cb068a78a)
2017-10-14 08:54:12,635 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://yearone-fullalbum (71707eab062ead18)
2017-10-14 08:54:12,710 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://themechanicalmonster (875b8322fd4d8af4)
```
```
2017-10-14 09:54:13,013 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://casually-successful (8d20e99a127c90c7)
2017-10-14 09:54:13,082 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (ea60d6af75107702)
2017-10-14 09:54:13,118 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (05e5315bec119349)
2017-10-14 09:54:13,154 WARNING  lbrynet.reflector.client.client:39: An error occurred immediately: Traceback (most recent call last):
  File "site-packages\twisted\internet\base.py", line 1208, in mainLoop
    
  File "site-packages\twisted\internet\base.py", line 801, in runUntilCurrent
    
  File "site-packages\twisted\internet\defer.py", line 457, in callback
    
  File "site-packages\twisted\internet\defer.py", line 565, in _startRunCallbacks
    
--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    
  File "site-packages\lbrynet\reflector\client\client.py", line 161, in <lambda>
    
exceptions.IndexError: list index out of range

2017-10-14 09:54:13,157 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (a21e55fd35cff660)
2017-10-14 09:54:13,161 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://juliamichaels (6a54c4d93403400e)
2017-10-14 09:54:13,180 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://alexnmike (2b0967cd04686812)

```

```
2017-10-14 00:54:12,584 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (05e5315bec119349)
2017-10-14 00:54:12,611 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://juliamichaels (6a54c4d93403400e)
2017-10-14 00:54:12,618 WARNING  lbrynet.reflector.client.client:39: An error occurred immediately: Traceback (most recent call last):
  File "site-packages\twisted\internet\base.py", line 1208, in mainLoop
    
  File "site-packages\twisted\internet\base.py", line 801, in runUntilCurrent
    
  File "site-packages\twisted\internet\defer.py", line 457, in callback
    
  File "site-packages\twisted\internet\defer.py", line 565, in _startRunCallbacks
    
--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    
  File "site-packages\lbrynet\reflector\client\client.py", line 161, in <lambda>
    
exceptions.IndexError: list index out of range

2017-10-14 00:54:12,641 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://alexnmike (2b0967cd04686812)
2017-10-14 00:54:12,693 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (a21e55fd35cff660)
2017-10-14 00:54:12,703 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (8244cc5172e04f63)
```

```
2017-10-14 01:54:12,430 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://casually-successful (8d20e99a127c90c7)
2017-10-14 01:54:12,463 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (05e5315bec119349)
2017-10-14 01:54:12,463 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (ea60d6af75107702)
2017-10-14 01:54:12,499 WARNING  lbrynet.reflector.client.client:39: An error occurred immediately: Traceback (most recent call last):
  File "site-packages\twisted\internet\base.py", line 1208, in mainLoop
    
  File "site-packages\twisted\internet\base.py", line 801, in runUntilCurrent
    
  File "site-packages\twisted\internet\defer.py", line 457, in callback
    
  File "site-packages\twisted\internet\defer.py", line 565, in _startRunCallbacks
    
--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    
  File "site-packages\lbrynet\reflector\client\client.py", line 161, in <lambda>
    
exceptions.IndexError: list index out of range

2017-10-14 01:54:12,517 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://alexnmike (2b0967cd04686812)
2017-10-14 01:54:12,549 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://juliamichaels (6a54c4d93403400e)

```

```
2017-10-14 02:54:12,562 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://alexnmike (2b0967cd04686812)
2017-10-14 02:54:12,572 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://juliamichaels (6a54c4d93403400e)
2017-10-14 02:54:12,576 WARNING  lbrynet.reflector.client.client:39: An error occurred immediately: Traceback (most recent call last):
  File "site-packages\twisted\internet\base.py", line 1208, in mainLoop
    
  File "site-packages\twisted\internet\base.py", line 801, in runUntilCurrent
    
  File "site-packages\twisted\internet\defer.py", line 457, in callback
    
  File "site-packages\twisted\internet\defer.py", line 565, in _startRunCallbacks
    
--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    
  File "site-packages\lbrynet\reflector\client\client.py", line 161, in <lambda>
    
exceptions.IndexError: list index out of range

2017-10-14 02:54:12,595 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (a21e55fd35cff660)
2017-10-14 02:54:12,628 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (8244cc5172e04f63)
2017-10-14 02:54:12,691 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (31f8411cb068a78a)
2017-10-14 02:54:12,710 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://yearone-fullalbum (71707eab062ead18)
```
```
2017-10-14 03:54:13,427 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://juliamichaels (6a54c4d93403400e)
2017-10-14 03:54:13,428 WARNING  lbrynet.reflector.client.client:39: An error occurred immediately: Traceback (most recent call last):
  File "site-packages\twisted\internet\base.py", line 1208, in mainLoop
    
  File "site-packages\twisted\internet\base.py", line 801, in runUntilCurrent
    
  File "site-packages\twisted\internet\defer.py", line 457, in callback
    
  File "site-packages\twisted\internet\defer.py", line 565, in _startRunCallbacks
    
--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    
  File "site-packages\lbrynet\reflector\client\client.py", line 161, in <lambda>
    
exceptions.IndexError: list index out of range

2017-10-14 03:54:13,493 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (8244cc5172e04f63)
2017-10-14 03:54:13,559 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://None (31f8411cb068a78a)
2017-10-14 03:54:13,576 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://themechanicalmonster (875b8322fd4d8af4)
```

**Comment by lyoshenka** [comment]
@kaykurokawa is this fixed?
