### ISSUE TITLE
configs sets HOSTS wrong? 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/reflector-cluster#4]
I think HOSTS is supposed to just be a list of strings ? 

https://github.com/lbryio/reflector-cluster/blob/master/prism/config.py#L32

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq-0.8.0-py2.7.egg/rq/worker.py", line 710, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq-0.8.0-py2.7.egg/rq/job.py", line 560, in perform
    self._result = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/rq-0.8.0-py2.7.egg/rq/job.py", line 566, in _execute
    return self.func(*self.args, **self.kwargs)
  File "build/bdist.linux-x86_64/egg/prism/protocol/task.py", line 57, in process_blob
    host, port, host_blob_count = next_host()
  File "build/bdist.linux-x86_64/egg/prism/protocol/task.py", line 39, in next_host
    if ":" in host:

**Comment by jackrobison** [comment]
https://github.com/lbryio/reflector-cluster/commit/4ca8c4daae2be6023232e0949a60579e10e892b0
